global:
  slack_api_url: 'https://hooks.slack.com/services/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'
  pagerduty_url: 'https://events.pagerduty.com/generic/2010-04-15/create_event.json'

route:
  receiver: 'pagerduty-notifications'
  group_by: ['alertname','instance','severity']


  routes:
    - receiver: "pagerduty-notifications"
      group_wait: 10s
      match_re:
        severity: critical|warning

    - receiver: "slack-notifications"
      group_wait: 10s
      match_re:
        severity: critical|warning


receivers:
- name: 'pagerduty-notifications'
  pagerduty_configs:
  - service_key: 47d275cf531e440bd09e7e938b9e739d
    send_resolved: true


- name: 'slack-notifications'
  slack_configs:
  # CHANGE THE CHANNEL NAME
  - channel: '#alert_channel'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.instance }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}